services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    memswap_limit: 4G

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: indy
      POSTGRES_PASSWORD: indy-db
      POSTGRES_DB: indy_db
    ports:
      - '5555:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
